
name: 'GitHub Actions Mirror'

on: 
  # 触发条件 push操作
  push:
    # 触发分支 main分支
    branches: [main]

jobs:
  # 同步到GitLab
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Mirror to gitlab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          # 目标GitLab仓库
          target_repo_url:
            git@git.test.cn:Derek/test.git
          ssh_private_key:
            ${{ secrets.GITLAB_KEY }}
  
  # 同步到Gitee
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Mirror to gitee
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          # 目标Gitee仓库
          target_repo_url:
            git@gitee.com:derek_nlp/nlp-arxiv-daily-for-lab.git
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}
